name: PR Build and Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Install dependencies
        run: go get -d

      - name: Build
        run: go build -v

      - name: Run tests
        run: go test -v ./...

      - name: Run tests with race detector
        run: go test -race -short ./...
